eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8700/eureka/
server:
  port: 8789
spring:
  application:
    name: zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: ribbon
    api-b:
      path: /api-b/**
      serviceId: feign